{{- $annotations := .Values.ingress.annotations }}
{{- $defaultBodySize := .Values.ingress.bodySize.default | quote }}
{{- $transcriptionBodySize := .Values.ingress.bodySize.transcription | quote }}
{{- $host := .Values.ingress.host | quote }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress-auth
  annotations:
    {{- toYaml $annotations | nindent 4 }}
    haproxy-ingress.github.io/proxy-body-size: {{ $defaultBodySize }}
spec:
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress-transcription
  annotations:
    {{- toYaml $annotations | nindent 4 }}
    haproxy-ingress.github.io/proxy-body-size: {{ $transcriptionBodySize }}
spec:
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /transcription
            pathType: Prefix
            backend:
              service:
                name: transcription-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress-translation
  annotations:
    {{- toYaml $annotations | nindent 4 }}
    haproxy-ingress.github.io/proxy-body-size: {{ $defaultBodySize }}
spec:
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /translation
            pathType: Prefix
            backend:
              service:
                name: translation-service
                port:
                  number: 80
{{- if .Values.ingress.enableDocs }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress-docs
  annotations:
    {{- toYaml $annotations | nindent 4 }}
    haproxy-ingress.github.io/proxy-body-size: {{ $defaultBodySize }}
spec:
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: docs-service
                port:
                  number: 80
{{- end }}
