{{- if eq (include "fastapi-base.hasSecrets" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-base.name" . }}-secrets
type: Opaque
data:
  {{- $chartName := include "fastapi-base.name" . -}}
  {{- $globalSecrets := .Values.global.secrets -}}
  {{- range .Values.secrets }}
    {{- $secretValue := index $globalSecrets . }}
    {{- if $secretValue }}
    {{ . }}: {{ $secretValue | b64enc | quote }}
    {{- else }}
    {{- fail (printf "\n[ERROR] '%s': No value provided for global.secrets.%s" $chartName .) }}
    {{- end }}
  {{- end }}
{{- end }}
