ingress:
  annotations:
    kubernetes.io/ingress.class: "haproxy"
  host: "saysend-stage-002.k8s-dev.saysend.me"
  enableDocs: true
postgres:
  volumeSize: 1Gi
  instances: 1
  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 2000Mi
