docs:
  enabled: false

auth-service:
  env:
    - name: DB_HOST
      value: "prod-db-cluster.internal"
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: saysend.prod
          key: db_username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: saysend.prod
          key: db_password
