name: 'Cleanup Dynamic Environment'

on:
  delete

concurrency:
  group: deployment-${{ github.event.ref }}
  cancel-in-progress: true

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch' && startsWith(github.event.ref, 'stage/')
    steps:
    - name: Checkout infrastructure repo
      uses: actions/checkout@v4

    - name: Resolve namespace
      run: |
        IMAGE_TAG="$(echo '${{ github.event.ref }}' | sed 's/\//-/g')"
        echo "NAMESPACE=saysend-${IMAGE_TAG}" >> $GITHUB_ENV

    - name: Setup Kubernetes Environment
      uses: ./.github/actions/k8s-env-setup
      with:
        kubeconfig_base64: ${{ secrets.KUBECONFIG_DATA_STAGE }}
        namespace: ${{ env.NAMESPACE }}

    - name: Purge Helm Releases and Namespace
      run: |
        NS="${{ env.NAMESPACE }}"
        helm uninstall app -n ${NS} || true
        helm uninstall infra -n ${NS} || true
        kubectl delete namespace ${NS} --wait=true || true

    - name: Cleanup Kubeconfig
      if: always()
      uses: ./.github/actions/k8s-cleanup
