name: 'Deploy Platform Components'

on:
  repository_dispatch:
    types: [deploy-services]

concurrency:
  group: deployment-${{ github.event.client_payload.is_prod == 'true' && 'prod' || github.event.client_payload.image_tag }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: main
      ENV_NAME: prod
      NAMESPACE: saysend-prod
    steps:
    - name: Checkout infrastructure repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: 'main'

    - name: Prepare Stage Branch & Environment
      if: github.event.client_payload.is_prod != 'true'
      run: |
        GIT_REF="${{ github.event.client_payload.ref_name }}"
        IMAGE_TAG="${{ github.event.client_payload.image_tag }}"
        echo "TARGET_BRANCH=${GIT_REF}" >> $GITHUB_ENV
        echo "ENV_NAME=stage" >> $GITHUB_ENV
        echo "NAMESPACE=saysend-${IMAGE_TAG}" >> $GITHUB_ENV
        if git ls-remote --exit-code --heads origin "$GIT_REF"; then
          git fetch origin "$GIT_REF":refs/remotes/origin/"$GIT_REF"
          git checkout "$GIT_REF"
        else
          git checkout -b "$GIT_REF"
        fi

    - name: Install yq
      uses: mikefarah/yq@v4.44.1

    - name: Update Microservices Image Tags
      run: |
        TAG="${{ github.event.client_payload.image_tag }}"
        TARGET_FILE="./components/apps/values.yaml"
        yq -i "
          .auth-service.image.tag = \"${TAG}\" |
          .transcription-service.image.tag = \"${TAG}\" |
          .translation-service.image.tag = \"${TAG}\"
        " "${TARGET_FILE}"

    - name: Bump Chart and App Versions (Prod Only)
      if: env.ENV_NAME == 'prod'
      run: |
        TAG="${{ github.event.client_payload.image_tag }}"
        APPS_CHART="./components/apps/Chart.yaml"
        yq -i ".appVersion = \"${TAG}\"" "${APPS_CHART}"
        yq -i '.version = (.version | split(".") | .[-1] |= ((. | to_number) + 1 | to_string) | join("."))' "${APPS_CHART}"

    - name: Update Stage Dynamic Domain
      if: env.ENV_NAME == 'stage'
      run: |
        TARGET_FILE="./components/infra/values.yaml"
        TARGET_DOMAIN="${{ env.NAMESPACE }}.k8s-dev.saysend.me"
        yq -i ".ingress.host = \"${TARGET_DOMAIN}\"" "${TARGET_FILE}"

    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update configurations for target ${{ env.NAMESPACE }}"
        file_pattern: 'components/**/*.yaml'
        branch: ${{ env.TARGET_BRANCH }}
        create_branch: true

    - name: Setup Kubernetes Environment
      uses: ./.github/actions/k8s-env-setup
      with:
        kubeconfig_base64: ${{ env.ENV_NAME == 'prod' && secrets.KUBECONFIG_DATA_PROD || secrets.KUBECONFIG_DATA_STAGE }}
        namespace: ${{ env.NAMESPACE }}
        nexus_docker_config_base64: ${{ secrets.NEXUS_DOCKER_CONFIG }}

    - name: Deploy Infrastructure
      if: env.ENV_NAME == 'stage'
      run: |
        helm upgrade --install infra ./components/infra \
          -f ./components/infra/values.yaml \
          --namespace ${{ env.NAMESPACE }} --create-namespace

    - name: Deploy Applications
      run: |
        CURRENT_DATE=$(date +%s)
        rm -rf ./components/apps/charts/*
        rm -f ./components/apps/Chart.lock
        helm dependency build ./components/apps
        helm upgrade --install app ./components/apps \
          -f ./components/apps/values.yaml \
          -f ./components/apps/environments/${{ env.ENV_NAME }}.yaml \
          --set "global.deployDate=${CURRENT_DATE}" \
          --namespace ${{ env.NAMESPACE }} --create-namespace

    - name: Cleanup Kubeconfig
      if: always()
      uses: ./.github/actions/k8s-cleanup
