name: 'Deploy Platform Components'

on:
  push:
    branches:
      - 'stage/**'
    tags:
      - '[0-9]*'
  workflow_dispatch:

concurrency:
  group: deployment-${{ github.ref_type == 'tag' && 'prod' || github.ref_name }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.ref_type == 'branch' && startsWith(github.event.head_commit.message, '[deploy]'))
    steps:
    - name: Checkout infrastructure repo
      uses: actions/checkout@v4

    - name: Resolve environment
      run: |
        if [ "${{ github.ref_type }}" = "tag" ]; then
          echo "ENV_NAME=prod" >> $GITHUB_ENV
          echo "NAMESPACE=saysend-prod" >> $GITHUB_ENV
        else
          IMAGE_TAG="$(echo '${{ github.ref_name }}' | sed 's/\//-/g')"
          echo "ENV_NAME=stage" >> $GITHUB_ENV
          echo "NAMESPACE=saysend-${IMAGE_TAG}" >> $GITHUB_ENV
        fi

    - name: Setup Kubernetes Environment
      uses: ./.github/actions/k8s-env-setup
      with:
        kubeconfig_base64: ${{ env.ENV_NAME == 'prod' && secrets.PROD_KUBECONFIG_DATA || secrets.STAGE_KUBECONFIG_DATA }}
        namespace: ${{ env.NAMESPACE }}
        nexus_docker_config_base64: ${{ secrets.NEXUS_DOCKER_CONFIG }}

    - name: Deploy Infrastructure
      if: env.ENV_NAME == 'stage'
      run: |
        helm upgrade --install infra ./components/infra \
          -f ./components/infra/values.yaml \
          --namespace ${{ env.NAMESPACE }} --create-namespace

    - name: Create Stage Application Secrets
      if: env.ENV_NAME == 'stage'
      run: |
        kubectl create secret generic saysend.stage \
          --from-literal=jwt_secret_key="${{ secrets.STAGE_JWT_SECRET_KEY }}" \
          --from-literal=openai_api_key="${{ secrets.STAGE_OPENAI_API_KEY }}" \
          --from-literal=elevenlabs_api_key="${{ secrets.STAGE_ELEVENLABS_API_KEY }}" \
          --namespace ${{ env.NAMESPACE }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy Applications
      run: |
        CURRENT_DATE=$(date +%s)
        helm dependency build ./components/apps
        helm upgrade --install app ./components/apps \
          -f ./components/apps/values.yaml \
          -f ./components/apps/environments/${{ env.ENV_NAME }}.yaml \
          --set "global.deployDate=${CURRENT_DATE}" \
          --namespace ${{ env.NAMESPACE }} --create-namespace

    - name: Cleanup Kubeconfig
      if: always()
      uses: ./.github/actions/k8s-cleanup
