global:
  deployDate: ""
  secrets: {} # Populated dynamically via CI/CD --set flags

docs:
  enabled: false

docs-service:
  image:
    repository: swaggerapi/swagger-ui
    tag: "v5.17.14"
  service:
    targetPort: 8080
  secrets: []
  env:
    - name: BASE_URL
      value: "/docs"
    - name: URLS
      value: |-
        [
          {"url": "/auth/openapi.json","name":"Auth API"},
          {"url": "/transcription/openapi.json","name": "Transcription API"},
          {"url": "/translation/openapi.json","name": "Translation API"}
        ]

auth-service:
  image:
    repository: docker-registry.lifeulike.net/saysend/auth
    tag: "latest"
  migrations:
    enabled: true
  secrets:
    - JWT_SECRET_KEY

transcription-service:
  image:
    repository: docker-registry.lifeulike.net/saysend/transcription
    tag: "latest"
  secrets:
    - JWT_SECRET_KEY
    - ELEVENLABS_API_KEY
    - OPENAI_API_KEY

translation-service:
  image:
    repository: docker-registry.lifeulike.net/saysend/translation
    tag: "latest"
  migrations:
    enabled: true
  secrets:
    - JWT_SECRET_KEY
    - OPENAI_API_KEY
